name: charts_flutter
version: 0.11.0
description: Material Design charting library for flutter.
author: Charts Team <charts_flutter@google.com>
homepage: https://github.com/google/charts
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  intl: ^0.17.0
  logging: ^1.0.1
  meta: ^1.3.0
  charts_common::
    git:
      url: git@github.com:eaglebk/flutter-chart.git
      ref: hight_res_time

dev_dependencies:
  mockito: ^5.0.14
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  test: ^1.16.8
